# do not touch this value
file-version: 1
#REMEMBER TO MAKE THIS SHIT COMPATIBLE WITH LUCKPERMS

#   [=============]
#   [  PROXYCHAT  ]
#   [=============]

proxy-name: "Main-Velocity-Proxy"

# [ MESSAGE FORMAT ]
# formats the messages using placeholders
# if ranks are disabled, the prefix placeholder will also be disabled
# these are currently not compatible with other plugins
# %prefix% = player rank prefix
# %player% = username of sender
# %message% = raw text message from player
# %server% = server message was sent from
# %proxy-name% = name of proxy
message-format: "&7[&a%server%&7] %prefix% %player% &f: %message%"

# [ RANKS ]
# What system do you want to use for visual ranks?
# Options: ProxyChat, xProxy, none (LuckPerms compatibility soon? [prob not] )
rank-system: "ProxyChat"


# [ CHANNELS ]
# servers in the same channel will share player messages
# put servers you do NOT want to share messages into channel '0'
# any server not put in a channel will have its player messages disabled
# When using xProxy, the message channels work across different proxies
# null channels are ignored

# Make sure to populate the channels in order ( 1,2,3,4,5...).  {channel 0 is counted separately, it CAN be null}
# The plugin will stop scanning channels when it reaches an empty channel
# Servers not listed will have their player chat disabled
channels:
  0: # put independent servers here (channel 0 is for servers that do NOT share messages)
    - "banned-players" # These three servers will NOT share messages
    - "survival"
    - "creative"
  1:
    - "lobby_1"  # The three lobbies will share messages
    - "lobby_2"
    - "lobby_3"
  2:
  3:
  4:
  5:
  6:
  7:
  8:
# if you ever need more than 8 channels then just add more to the config

# Reports failed to send messages to console
# (it is only recommended to disable this if you are muting a server on purpose)
reportFailedMessages: true

# [ Moderation ]
# every time a player sends a message, it increments a counter
# every x milliseconds that counter is decremented
# if a player hits the max messages on their counter, their  messages are not shown to other players
spam-limiter:
  enabled: true
  counter-ceiling: 5 # if a player's message counter goes above this number, their messages will be hidden to other players
  decrement-timer: 4000 # milliseconds between message counter decrements
# logs are stored in /plugins/ProxyChat/logs/log_mm-dd-yyyy.txt
log-messages: true

# [ X PROXY ]
# allow multiple instances of ProxyChat to communicate
# useful for servers with multiple proxies
xProxy:
  enable: false
  xProxy-server-ip: '127.0.0.1'
  xProxy-server-port: 25599
  password: "P@ssword" # set to same value as in xProxy config

